id: I93DD9EA3
ocr_import_info:
  timestamp: '2023-08-16T09:01:01.261260+00:00'
  batch_id: batch-b4aa
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Tenzin Jordhen
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-08-16 12:25:38.966671+00:00
last_modified: 2023-08-16 12:25:38.966679+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN3014
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN3014
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྩ་འགྲེལ་གཞུང་བཤད་སོགས་ལག་བྲིས་དཔེ་རྙིང་པར་སློག་ཕྱོགས་བསྡུས།
  languages:
  - bo
statistics:
  ocr_word_mean_confidence_index: 0.8736216220082144
  ocr_word_median_confidence_index: 0.923179425
bases:
  I3CN445:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN445
      total_pages: 906
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I3CN445.txt
    statistics:
      ocr_word_median_confidence_index: 0.9133377
      ocr_word_mean_confidence_index: 0.8693259426510472
  I3CN449:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN449
      total_pages: 584
      volume_number: 11
      volume_pages_bdrc_intro: 2
    order: 11
    base_file: I3CN449.txt
    statistics:
      ocr_word_median_confidence_index: 0.9033354
      ocr_word_mean_confidence_index: 0.8539685332043335
  I3CN443:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN443
      total_pages: 918
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I3CN443.txt
    statistics:
      ocr_word_median_confidence_index: 0.9431803350000001
      ocr_word_mean_confidence_index: 0.8887645370885886
  I3CN440:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN440
      total_pages: 505
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I3CN440.txt
    statistics:
      ocr_word_median_confidence_index: 0.89405295
      ocr_word_mean_confidence_index: 0.8481122222461533
  I3CN444:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN444
      total_pages: 582
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I3CN444.txt
    statistics:
      ocr_word_median_confidence_index: 0.9183632
      ocr_word_mean_confidence_index: 0.8686127113960163
  I3CN446:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN446
      total_pages: 420
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I3CN446.txt
    statistics:
      ocr_word_median_confidence_index: 0.937082075
      ocr_word_mean_confidence_index: 0.8883494003576213
  I3CN439:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN439
      total_pages: 550
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN439.txt
    statistics:
      ocr_word_median_confidence_index: 0.9596201
      ocr_word_mean_confidence_index: 0.9011745506797445
  I3CN447:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN447
      total_pages: 610
      volume_number: 9
      volume_pages_bdrc_intro: 2
    order: 9
    base_file: I3CN447.txt
    statistics:
      ocr_word_median_confidence_index: 0.925743785
      ocr_word_mean_confidence_index: 0.8744546939606744
  I3CN442:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN442
      total_pages: 566
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I3CN442.txt
    statistics:
      ocr_word_median_confidence_index: 0.90038615
      ocr_word_mean_confidence_index: 0.846616857089516
  I3CN448:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN448
      total_pages: 932
      volume_number: 10
      volume_pages_bdrc_intro: 2
    order: 10
    base_file: I3CN448.txt
    statistics:
      ocr_word_median_confidence_index: 0.9316953299999999
      ocr_word_mean_confidence_index: 0.8864271534910279
  I3CN450:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN450
      total_pages: 522
      volume_number: 12
      volume_pages_bdrc_intro: 2
    order: 12
    base_file: I3CN450.txt
    statistics:
      ocr_word_median_confidence_index: 0.93631168
      ocr_word_mean_confidence_index: 0.8853646549107328
  I3CN441:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN441
      total_pages: 444
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I3CN441.txt
    statistics:
      ocr_word_median_confidence_index: 0.9024866
      ocr_word_mean_confidence_index: 0.8581821964343004
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
